jpackage --input target/ \
  --name JPafBoard \
  --main-jar JPafBoard-2.4-shaded.jar \
  --main-class com.paf.jpafboard.Main \
  --app-version 2.4 \
  --icon logo/icon.png \
  --vendor "PAF Fournié" \
  --license-file LICENSE.md \
  --about-url  "https://github.com/fournip1/jpafboard" \
  --linux-shortcut \
  --type deb \
  --java-options '--enable-preview'
